### ISSUE TITLE
Add timeout to policy evaluation

### ISSUE THREAD

**Issue by jvanz** [kubewarden/policy-server#254]
To help the mitigation of the [threat #2](https://github.com/kubewarden/rfc/blob/main/rfc/0006-threat-model.md#threat-2---attacker-passes-workloads-which-require-complex--processing-causing-timeouts) of the threat model, the policy server should allow the operator define a timeout for the policy evaluation. If a policy takes more then the defined timeout, the request is rejected. 

**NOTE:** This is an issue created from RFC discussing the admission control threat model. It's created to allow the Kubewarden team discuss the proposed mitigation further and start to work on each actionable item when possible

## Actions

* [x] Update policy-evaluator: https://github.com/kubewarden/policy-evaluator/pull/224
* [x] Update policy server: https://github.com/kubewarden/policy-server/pull/389
* [x] Update docs: https://github.com/kubewarden/docs/issues/157
* ~~ [ ] Blog post: https://github.com/kubewarden/kubewarden.io/issues/165 ~~

**Comment by flavio** [comment]
I think there are basically two options:

* Implement a timer
* Try to use something fancy like the [fuel](https://docs.rs/wasmtime/0.39.1/wasmtime/struct.Config.html#method.consume_fuel) concept built into wasmtime

**Comment by flavio** [comment]
I wonder if "timeout protection" is a good name for this feature :thinking: 

I think we should think about another one, because this is a bit confusing

**Comment by viccuad** [comment]
I'm having trouble finding a better wording for "if policy timeout reached, reject request".
Ideas: `rejection by timeout`, `timeout exclusion`.
I still prefer `timeout protection`.

**Comment by viccuad** [comment]
https://github.com/kubewarden/policy-server/pull/389 got prematurely merged, https://github.com/kubewarden/policy-server/pull/396 reverted it.

Re-opening card again. We would need to create a new PR analogous to https://github.com/kubewarden/policy-server/pull/389.

**Comment by flavio** [comment]
reopening, there are other tasks that have to be done
