### ISSUE TITLE
Enrich policies with metadata

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#61]
# What

We want to enrich each policy by adding some metadata to it. This information will be provided by the policy author.

# Why

Adding metatadata to the policy will allow us to do things as:

* Version policy files. We've already changed the communication protocol between the host (e.g. the policy server) and the guest (the actual policy). By versioning the policy we can for example prevent too old policies from being loaded by the policy-server/kwctl
* Provide a better UX for the end users. Right now the end users have to provide quite some information when creating a `ClusterAdmissionPolicy` resource. If the user enters the wrong information (e.g. he states a policy designed to process `Pod` resources can handle also `Deployment` resources), the policy evaluation can be totally broken/provide wrong results. The policy metadata will provide these information, and `kwctl` can then be used to scaffold correct definitions of the `ClusterAdmissionPolicy` resource

# How

The metadata of a single policy would look like that:

```json
{
  "policyVersion": "v1alpha1",
  "rules": [
    {
      "apiGroups":[""],
      "apiVersions":["v1"],
      "resources":["pods"],
      "operations":["CREATE"]
    }
  ]
}
```

The `rules` section is a has all the required fields of [admission registration config](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#rulewithoperations-v1-admissionregistration-k8s-io).

Each policy would have to expose a `metadata` guest call, that will return this object. This metadata will also be duplicated inside of the `custom section` of the resulting Wasm file.

We want to have the metadata into the `custom section` of the Wasm file too because this allows to inspect a Wasm module without evaluating that. The evaluation process of a Wasm module can take significant time, depending on how the originating compiler built the Wasm file.

# Linked cards

## Policy server:
* [x] [Add some way to version our policy wasm file](https://github.com/kubewarden/policy-server/issues/29)

## kwctl
* [x] [Create `annotate` subcommand](https://github.com/kubewarden/kwctl/issues/8)

## sdks
* [x] [Rust](https://github.com/kubewarden/policy-sdk-rust/issues/11)
* [x] [Go](https://github.com/kubewarden/policy-sdk-go/issues/5)
* [x] [Swift](https://github.com/kubewarden/policy-sdk-swift/issues/1)
* [x] AssemblyScript: update the existing policy

## Workflows
* [x] [policy author workflow](https://github.com/kubewarden/kwctl/issues/29)
* [x] [kubernetes administrator workflow](https://github.com/kubewarden/kwctl/issues/28)

## Docs
* [x] [Update docs](https://github.com/kubewarden/docs/issues/38)

**Comment by flavio** [comment]
Done
