### ISSUE TITLE
Feature Request: add host capability to retreive OCI manifests

### ISSUE THREAD

**Issue by zarbis** [kubewarden/policy-server#638]
### Is your feature request related to a problem?

I want to create a policy that would inject supported platforms info into pod's `spec.affinity.nodeAffinity`.
In order to do so I need to query OCI registry for each container image's manifest and extract list of supported platforms.
Right now it's not possible due to lack of networking support inside WASM module.

### Solution you'd like

I would like policy-server to expose new host capability `v1/manifest` that would expose full OCI manifest of a given image.
Note: there is an existing capability `v1/manifest_digest` that does similar thing.

### Acceptance criteria:

> This section came from a comment. There for we can use Github feature to create subtasks and keep track of the progress. 

- [x] kubewarden/docs#346
- [x] kubewarden/policy-evaluator#428
- [x] kubewarden/kwctl#707
- [x] kubewarden/policy-server#653
- [x] kubewarden/policy-sdk-rust#128
- [x] kubewarden/policy-sdk-go#68
- [ ] kubewarden/kubewarden.io#211

Once this is done, it will be part of the next release of KW (1.11.0)

**Comment by flavio** [comment]
This is definitely doable. We are currently in the process or releasing Kubewarden 1.10. I think this is something we can achieve with the 1.11 release.

**Comment by flavio** [comment]
Acceptance criteria:

- [ ] Implement the host capability inside of policy-evaluator
- [ ] Consume latest version of policy-evaluator from kwctl and policy-server
- [ ] Extend the Rust SDK to expose this new capability
- [ ] Extend the Go SDK to expose this new capability
- [ ] Update the docs section about the protocol specification to document this new capability
- [ ] Blog post about this feature

Once this is done, it will be part of the next release of KW (1.11.0)

**Comment by jvanz** [comment]
@kubewarden/kubewarden-developers , I've open a bunch PR adding this new capability. To test all of them, I've create a very simple policy which just prints the return the response of the new `v1/oci_manifest` capability and accept the request. The validation code is the following:

```rust
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: ValidationRequest<Settings> = ValidationRequest::new(payload)?;

    match serde_json::from_value::<apicore::Pod>(validation_request.request.object) {
        Ok(pod) => {
            let manifests: Vec<oci::OciManifestResponse> = pod
                .spec
                .as_ref()
                .unwrap()
                .containers
                .iter()
                .map(|container| { oci::manifest(&container.image.clone().unwrap_or_default()).unwrap()})
                .collect();

            println!("{:?}", serde_json::to_string(&manifests).expect("failed to parse manifests"));
        }
        Err(_) => {
            warn!(LOG_DRAIN, "cannot unmarshal resource: this policy does not know how to evaluate this resource; accept it");
        }
    }
    kubewarden::accept_request()
}
```

Then, I've run the policy using kwctl with the new capability enabled to test the new feature:

```console
$ kwctl run  --request-path test_data/pod_creation.json  annotated-policy.wasm
2024-02-02T18:44:23.395844Z  INFO validate_settings{self=PolicyEvaluator { runtime: "wapc" } settings={}}:policy_log{self=EvaluationContext { policy_id: "node-affinity-policy", callback_channel: Some(...), allowed_kubernetes_resources: {} }}: policy_log: starting settings validation data={"column":9,"file":"src/settings.rs","line":14,"policy":"sample-policy"}
"[{\"schemaVersion\":2,\"mediaType\":\"application/vnd.oci.image.index.v1+json\",\"manifests\":[{\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"digest\":\"sha256:3aece2edc438b3007d49d4aade9a578bd0037140739ccfeff45e26dc97eb4cd2\",\"size\":1048,\"platform\":{\"architecture\":\"amd64\",\"os\":\"linux\"}},{\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"digest\":\"sha256:e6346de798dfa7f96bfff075367ff74d20480542b0361d78d5f048f040bf7931\",\"size\":1048,\"platform\":{\"architecture\":\"arm64\",\"os\":\"linux\"}},{\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"digest\":\"sha256:9bc837a161fe7cb1ae7e961738d86ae725e85315d9a349e65f34f108a1290b1d\",\"size\":566,\"annotations\":{\"vnd.docker.reference.type\":\"attestation-manifest\",\"vnd.docker.reference.digest\":\"sha256:3aece2edc438b3007d49d4aade9a578bd0037140739ccfeff45e26dc97eb4cd2\"},\"platform\":{\"architecture\":\"unknown\",\"os\":\"unknown\"}},{\"mediaType\":\"application/vnd.oci.image.manifest.v1+json\",\"digest\":\"sha256:8fc08a539302a1c586db7056604d51a817c55a2e12129908d7044f4c2172ccdd\",\"size\":566,\"annotations\":{\"vnd.docker.reference.digest\":\"sha256:e6346de798dfa7f96bfff075367ff74d20480542b0361d78d5f048f040bf7931\",\"vnd.docker.reference.type\":\"attestation-manifest\"},\"platform\":{\"architecture\":\"unknown\",\"os\":\"unknown\"}}]},{\"schemaVersion\":2,\"config\":{\"mediaType\":\"application/vnd.wasm.config.v1+json\",\"digest\":\"sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a\",\"size\":2},\"layers\":[{\"mediaType\":\"application/vnd.wasm.content.layer.v1+wasm\",\"digest\":\"sha256:f6c7d35cd019c8f46653bbe5caf32b3dca3d0a04c726d877f015671917355397\",\"size\":1285268}]}]"
{"uid":"1299d386-525b-4032-98ae-1949f69f9cfc","allowed":true,"auditAnnotations":null,"warnings":null}
```

To make more easy to read, this is the returned JSON:

```json
[
  {
    "schemaVersion": 2,
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "manifests": [
      {
        "mediaType": "application/vnd.oci.image.manifest.v1+json",
        "digest": "sha256:3aece2edc438b3007d49d4aade9a578bd0037140739ccfeff45e26dc97eb4cd2",
        "size": 1048,
        "platform": {
          "architecture": "amd64",
          "os": "linux"
        }
      },
      {
        "mediaType": "application/vnd.oci.image.manifest.v1+json",
        "digest": "sha256:e6346de798dfa7f96bfff075367ff74d20480542b0361d78d5f048f040bf7931",
        "size": 1048,
        "platform": {
          "architecture": "arm64",
          "os": "linux"
        }
      },
      {
        "mediaType": "application/vnd.oci.image.manifest.v1+json",
        "digest": "sha256:9bc837a161fe7cb1ae7e961738d86ae725e85315d9a349e65f34f108a1290b1d",
        "size": 566,
        "annotations": {
          "vnd.docker.reference.type": "attestation-manifest",
          "vnd.docker.reference.digest": "sha256:3aece2edc438b3007d49d4aade9a578bd0037140739ccfeff45e26dc97eb4cd2"
        },
        "platform": {
          "architecture": "unknown",
          "os": "unknown"
        }
      },
      {
        "mediaType": "application/vnd.oci.image.manifest.v1+json",
        "digest": "sha256:8fc08a539302a1c586db7056604d51a817c55a2e12129908d7044f4c2172ccdd",
        "size": 566,
        "annotations": {
          "vnd.docker.reference.digest": "sha256:e6346de798dfa7f96bfff075367ff74d20480542b0361d78d5f048f040bf7931",
          "vnd.docker.reference.type": "attestation-manifest"
        },
        "platform": {
          "architecture": "unknown",
          "os": "unknown"
        }
      }
    ]
  },
  {
    "schemaVersion": 2,
    "config": {
      "mediaType": "application/vnd.wasm.config.v1+json",
      "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
      "size": 2
    },
    "layers": [
      {
        "mediaType": "application/vnd.wasm.content.layer.v1+wasm",
        "digest": "sha256:f6c7d35cd019c8f46653bbe5caf32b3dca3d0a04c726d877f015671917355397",
        "size": 1285268
      }
    ]
  }
]
```

The capability is working. I think we can start the process of merging the PRs.

**Comment by jvanz** [comment]
@zarbis we just release the `v1.11.0-rc1` with this feature included on it. We will be happy if you test it as well. You can see an example of how to use the new capability in the [blog post draft](https://github.com/kubewarden/kubewarden.io/pull/212).

**Comment by flavio** [comment]
Kubewarden 1.11 is out, this feature is available 🥳 

We will publish the blog post next Monday

**Comment by jvanz** [comment]
The blog post with a simple example of the usage of this new capability is available: https://www.kubewarden.io/blog/2024/03/oci-manifest-capability/
