### ISSUE TITLE
Allow policies to produce log messages

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#73]
This doesn't strictly belong to policy-server, but it's obviously related.

We should allow policies to produce log messages when being executed. These log messages should be shown inside of policy-server logs.

# Acceptance criteria

* Policy author have logging API that allow them to produce log messages with different level (eg: debug, info, warning, error)
* The policy SDKs are extended to provide easy access to "log creation"
* policy-server shows these logs

# Linked cards

* [x] [Expose host callback for logging](https://github.com/kubewarden/policy-evaluator/issues/12)
* [x] [Rust SDK: provide logging api](https://github.com/kubewarden/policy-sdk-rust/issues/15)
* [x] [Go SDK: provide logging api](https://github.com/kubewarden/policy-sdk-go/issues/9)
* [ ] [Swift SDK: provide logging api](https://github.com/kubewarden/policy-sdk-swift/issues/2)

**Comment by flavio** [comment]
Closing the issue, even though swift code isn't ready yet. We give swift a lower priority compared to the Rust and Go
