### ISSUE TITLE
feature: introduce feature flag that influences how policy server reacts to broken policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#730]
Policy Server quits when one of its policies cannot be downloaded or when the policy configuration is not valid. This has always been its behavior.

We recently introduced a change that causes policy server to not exit when one of these circumstances take place. Instead, the policy server keeps running but the requests sent to one of the broken policies are rejected with a special error message.

This can be confusing and lead to some unexpected scenarios.

Because of that we want the following changes to happen.

## Acceptance criteria

- [ ] A new feature flag + env variable (boolean one) is added to policy server. This determines if the policy server should exit on error or keep running
- [ ] By default the policy server should retain the old behavior
- [ ] We have to document this new feature flag, explaining why we did it and its limitations
- [ ] Advertise this feature as alpha, look for feedback from users

**Comment by flavio** [comment]
@fabriziosestito we've assigned that to you since you've already looked into this topic
